# Generated by Django 3.1.4 on 2020-12-25 19:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mensagem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 19, 47, 27, 686325, tzinfo=utc), editable=False, verbose_name='Data do Email'),
        ),
    ]
