# Generated by Django 3.1.4 on 2020-12-25 19:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mensagem', '0002_auto_20201225_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Data do Email'),
        ),
    ]
