# Generated by Django 3.1.4 on 2020-12-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mensagem', '0003_auto_20201225_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data do Email'),
        ),
    ]
